apiVersion: apps/v1
kind: Deployment
metadata:
  name: trainingjava
  labels:
    app: tomcat
  annotations:
    kubernetes.io/change-cause: Build no is test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: sathishbob/javaapp-k8s:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tomcatservice
spec:
  selector:
    app: tomcat
  ports:
  - protocol: TCP
    port: 8080
  type: LoadBalancer
